spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imooc-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: NEWlife_root4
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
#imooc:
#  security:
#    browser:
#      loginPage: /imooc-signIn.html
#      loginType: JSON
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user/*
imooc:
  security:
    browser:
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
    social:
      qq:
        app-id: sss
        app-secret: ss
        providerId: callback.do
      filterProcessesUrl: /qqLogin

server:
  port: 8080
  session:
    timeout: 600
